/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumGameGameResult } from "./EnumGameGameResult";
import { StringFilter } from "../../util/StringFilter";
import { EnumGameResult } from "./EnumGameResult";
import { TournamentGameListRelationFilter } from "../../tournamentGame/base/TournamentGameListRelationFilter";

@InputType()
class GameWhereInput {
  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  gamePlayedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  gamePlayer1?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  gamePlayer2?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumGameGameResult,
  })
  @IsEnum(EnumGameGameResult)
  @IsOptional()
  @Field(() => EnumGameGameResult, {
    nullable: true,
  })
  gameResult?: "Option1";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  playedAt?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  player1?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  player2?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumGameResult,
  })
  @IsEnum(EnumGameResult)
  @IsOptional()
  @Field(() => EnumGameResult, {
    nullable: true,
  })
  result?: "Option1";

  @ApiProperty({
    required: false,
    type: () => TournamentGameListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TournamentGameListRelationFilter)
  @IsOptional()
  @Field(() => TournamentGameListRelationFilter, {
    nullable: true,
  })
  tournamentGames?: TournamentGameListRelationFilter;
}

export { GameWhereInput as GameWhereInput };
