/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { TournamentGameListRelationFilter } from "../../tournamentGame/base/TournamentGameListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { TournamentPlayerListRelationFilter } from "../../tournamentPlayer/base/TournamentPlayerListRelationFilter";

@InputType()
class TournamentWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  tournamentEndDate?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TournamentGameListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TournamentGameListRelationFilter)
  @IsOptional()
  @Field(() => TournamentGameListRelationFilter, {
    nullable: true,
  })
  tournamentGames?: TournamentGameListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  tournamentName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TournamentPlayerListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TournamentPlayerListRelationFilter)
  @IsOptional()
  @Field(() => TournamentPlayerListRelationFilter, {
    nullable: true,
  })
  tournamentPlayers?: TournamentPlayerListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  tournamentStartDate?: DateTimeNullableFilter;
}

export { TournamentWhereInput as TournamentWhereInput };
