/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TournamentService } from "../tournament.service";
import { TournamentCreateInput } from "./TournamentCreateInput";
import { Tournament } from "./Tournament";
import { TournamentFindManyArgs } from "./TournamentFindManyArgs";
import { TournamentWhereUniqueInput } from "./TournamentWhereUniqueInput";
import { TournamentUpdateInput } from "./TournamentUpdateInput";
import { TournamentGameFindManyArgs } from "../../tournamentGame/base/TournamentGameFindManyArgs";
import { TournamentGame } from "../../tournamentGame/base/TournamentGame";
import { TournamentGameWhereUniqueInput } from "../../tournamentGame/base/TournamentGameWhereUniqueInput";
import { TournamentPlayerFindManyArgs } from "../../tournamentPlayer/base/TournamentPlayerFindManyArgs";
import { TournamentPlayer } from "../../tournamentPlayer/base/TournamentPlayer";
import { TournamentPlayerWhereUniqueInput } from "../../tournamentPlayer/base/TournamentPlayerWhereUniqueInput";

export class TournamentControllerBase {
  constructor(protected readonly service: TournamentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Tournament })
  async createTournament(
    @common.Body() data: TournamentCreateInput
  ): Promise<Tournament> {
    return await this.service.createTournament({
      data: data,
      select: {
        createdAt: true,
        id: true,
        tournamentEndDate: true,
        tournamentName: true,
        tournamentStartDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Tournament] })
  @ApiNestedQuery(TournamentFindManyArgs)
  async tournaments(@common.Req() request: Request): Promise<Tournament[]> {
    const args = plainToClass(TournamentFindManyArgs, request.query);
    return this.service.tournaments({
      ...args,
      select: {
        createdAt: true,
        id: true,
        tournamentEndDate: true,
        tournamentName: true,
        tournamentStartDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Tournament })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async tournament(
    @common.Param() params: TournamentWhereUniqueInput
  ): Promise<Tournament | null> {
    const result = await this.service.tournament({
      where: params,
      select: {
        createdAt: true,
        id: true,
        tournamentEndDate: true,
        tournamentName: true,
        tournamentStartDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Tournament })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTournament(
    @common.Param() params: TournamentWhereUniqueInput,
    @common.Body() data: TournamentUpdateInput
  ): Promise<Tournament | null> {
    try {
      return await this.service.updateTournament({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          tournamentEndDate: true,
          tournamentName: true,
          tournamentStartDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Tournament })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTournament(
    @common.Param() params: TournamentWhereUniqueInput
  ): Promise<Tournament | null> {
    try {
      return await this.service.deleteTournament({
        where: params,
        select: {
          createdAt: true,
          id: true,
          tournamentEndDate: true,
          tournamentName: true,
          tournamentStartDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/tournamentGames")
  @ApiNestedQuery(TournamentGameFindManyArgs)
  async findTournamentGames(
    @common.Req() request: Request,
    @common.Param() params: TournamentWhereUniqueInput
  ): Promise<TournamentGame[]> {
    const query = plainToClass(TournamentGameFindManyArgs, request.query);
    const results = await this.service.findTournamentGames(params.id, {
      ...query,
      select: {
        createdAt: true,

        game: {
          select: {
            id: true,
          },
        },

        id: true,

        tournament: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tournamentGames")
  async connectTournamentGames(
    @common.Param() params: TournamentWhereUniqueInput,
    @common.Body() body: TournamentGameWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tournamentGames: {
        connect: body,
      },
    };
    await this.service.updateTournament({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tournamentGames")
  async updateTournamentGames(
    @common.Param() params: TournamentWhereUniqueInput,
    @common.Body() body: TournamentGameWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tournamentGames: {
        set: body,
      },
    };
    await this.service.updateTournament({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tournamentGames")
  async disconnectTournamentGames(
    @common.Param() params: TournamentWhereUniqueInput,
    @common.Body() body: TournamentGameWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tournamentGames: {
        disconnect: body,
      },
    };
    await this.service.updateTournament({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/tournamentPlayers")
  @ApiNestedQuery(TournamentPlayerFindManyArgs)
  async findTournamentPlayers(
    @common.Req() request: Request,
    @common.Param() params: TournamentWhereUniqueInput
  ): Promise<TournamentPlayer[]> {
    const query = plainToClass(TournamentPlayerFindManyArgs, request.query);
    const results = await this.service.findTournamentPlayers(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        player: {
          select: {
            id: true,
          },
        },

        tournament: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tournamentPlayers")
  async connectTournamentPlayers(
    @common.Param() params: TournamentWhereUniqueInput,
    @common.Body() body: TournamentPlayerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tournamentPlayers: {
        connect: body,
      },
    };
    await this.service.updateTournament({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tournamentPlayers")
  async updateTournamentPlayers(
    @common.Param() params: TournamentWhereUniqueInput,
    @common.Body() body: TournamentPlayerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tournamentPlayers: {
        set: body,
      },
    };
    await this.service.updateTournament({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tournamentPlayers")
  async disconnectTournamentPlayers(
    @common.Param() params: TournamentWhereUniqueInput,
    @common.Body() body: TournamentPlayerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tournamentPlayers: {
        disconnect: body,
      },
    };
    await this.service.updateTournament({
      where: params,
      data,
      select: { id: true },
    });
  }
}
